title: "Lunch Time Thoughts"
remote_theme: "mmistakes/minimal-mistakes@4.19.3"
#theme: jekyll-theme-cayman
future: true
plugins: [jekyll-include-cache]

minimal_mistakes_skin: "air" # "default", "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum" "sunrise"